name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          load: true
          file: Dockerfile
          
      -
        name: Run Trivy vulnerability scanner for image (unknown, low & medium) 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'marcel1707/demo:latest'
          format: 'table'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM'
          exit-code: '0'
          
      -
        name: Run Trivy vulnerability scanner for image (Dockerfile)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL, HIGH'
          exit-code: '1'
          
      -
        name: Run Trivy vulnerability scanner for image (critical & high)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'marcel1707/demo:latest'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL, HIGH'
          exit-code: '1'
          
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: marcel1707/demo:latest, marcel1707/demo:${{github.sha}}
          
