name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          
      -
        name: Build and push
        uses: docker/build-push-action@v3
        env:
          GIT_SHA: "$(git rev-parse --short HEAD)"
        with:
          push: true
          tags: marcel1707/demo:latest, marcel1707/demo:$GIT_SHA
          
