name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build . --file Dockerfile --tag marcel1707/demo:latest --tag marcel1707/demo:$GIT_SHA
        docker push marcel1707/demo:latest
        docker push marcel1707/demo:$GIT_SHA
        
      
